version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "cedricziel"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "cedricziel"
    groups:
      symfony:
        patterns:
        - "symfony/*"
