<?php

namespace CedricZiel\MattermostPhp\Client\Model;

class CreateRemoteClusterResponse
{
    public function __construct(
        public $remote_cluster = null,
        /** The encrypted invite for the newly created remote cluster */
        public ?string $invite = null,
        /**
         * The password generated by the server if none was
         * sent on the create request
         */
        public ?string $password = null,
    ) {
    }

    /**
     * Hydrate a new instance from an array of data.
     *
     * @param array<string, mixed>|null $data The data to hydrate from
     * @return CreateRemoteClusterResponse The hydrated instance
     */
    public static function hydrate(?array $data): CreateRemoteClusterResponse
    {
        $data ??= [];

        return new self(
            remote_cluster: $data['remote_cluster'] ?? null,
            invite: $data['invite'] ?? null,
            password: $data['password'] ?? null,
        );
    }
}
