<?php

namespace CedricZiel\MattermostPhp\Client\Model;

class CreateRemoteClusterResponse
{
    public function __construct(
        public $remote_cluster = null,
        /** The encrypted invite for the newly created remote cluster */
        public ?string $invite = null,
        /**
         * The password generated by the server if none was
         * sent on the create request
         */
        public ?string $password = null,
    ) {
    }

    public static function hydrate(
        /** @param array<string, mixed> $data */
        ?array $data,
    ): CreateRemoteClusterResponse {
        $object = new self(
            remote_cluster: isset($data['remote_cluster']) ? $data['remote_cluster'] : null,
            invite: isset($data['invite']) ? $data['invite'] : null,
            password: isset($data['password']) ? $data['password'] : null,
        );
        return $object;
    }
}
